from uuid import UUID

from pydantic import (
    BaseModel,
    Field,
)

from src.active_ml.types import LabellingSpectrumSetType


class LabellingInitializeSerializer(BaseModel):
    """
    Serializer model for initializing a new labelling.
    """

    job_id: UUID = Field(
        ...,
        description="Unique identifier of the job under which to initialize the labelling",
    )

    spectrum_filename: str = Field(
        ...,
        min_length=1,
        max_length=70,
        description="Filename of the associated spectrum",
        examples=["spec-56207-M31011N44B2_sp01-006.fits"],
    )

    spectrum_set: LabellingSpectrumSetType = Field(
        ...,
        description="Dataset group in which this spectrum is evaluated for the current job",
    )

    sequence_iteration: int = Field(
        ...,
        ge=0,
        description="Zero‑based index of the ML job iteration within the job’s processing sequence",
        examples=[0],
    )

    model_prediction: str | None = Field(
        None,
        min_length=1,
        max_length=30,
        description="Optional initial prediction generated by the ML model for this spectrum",
        examples=["double-peak"],
    )
